# Generated by Django 4.2.19 on 2025-02-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wireguard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Current IP address')),
                ('registration_ip', models.GenericIPAddressField(help_text='IP address used during registration')),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User IP Addresses',
            },
        ),
        migrations.AlterField(
            model_name='wireguardconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wireguardconfig',
            name='private_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardconfig',
            name='public_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='wireguardconfig',
            index=models.Index(fields=['user'], name='wireguard_a_user_id_d070cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wireguardconfig',
            index=models.Index(fields=['ip_address'], name='wireguard_a_ip_addr_d04b6d_idx'),
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='registrationattempt',
            index=models.Index(fields=['ip_address'], name='wireguard_a_ip_addr_8a6b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='useripaddress',
            index=models.Index(fields=['ip_address'], name='wireguard_a_ip_addr_8e3527_idx'),
        ),
        migrations.AddIndex(
            model_name='useripaddress',
            index=models.Index(fields=['registration_ip'], name='wireguard_a_registr_141c3c_idx'),
        ),
    ]
